# Generated by Django 5.0.3 on 2024-03-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=100)),
                ('empDept', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField(null=True)),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=50)),
                ('joiningDate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
