# Generated by Django 5.0.3 on 2024-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorklogRecord', '0002_day_timeslot_rename_dateofbirth_employeedetail_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.AddField(
            model_name='day',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
