# Generated by Django 4.2.11 on 2024-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorklogRecord', '0003_remove_day_date_day_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('assigned_on', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
