# Generated by Django 5.0.3 on 2024-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorklogRecord', '0004_employeeworkdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='isAdmin',
            field=models.BooleanField(null=True),
        ),
    ]
